language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

install:
  - ln -s tests/travis/Sphinx/sphinx.conf sphinx.conf
  - sh tests/travis/Sphinx/install.sh

before_script:
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install

after_script:
  - php bin/coveralls -v

script:
  - bin/phpunit --coverage-text